### ISSUE TITLE
Font Error

### ISSUE THREAD

**Issue by SpiritCodes** [roefinoavrililo/Discord.JS-Leveling-Bot#3]
I have An Issue with the bot, whenever I do ``[prefix] rank`` it shows the card, but it doesn't show the font. The console says "Fontconfig error: Cannot load default config file" 

How do you fix this?

**Comment by SpiritCodes** [comment]
I saw this was posted in other Issues, so I'll be closing this. Please fix soon!

**Comment by roefinoavrililo** [comment]
have you installed the font?

**Comment by roefinoavrililo** [comment]
![image](https://user-images.githubusercontent.com/68174038/124670482-3fd59500-dede-11eb-990d-a7ecb4ec368e.png)
have you tried to install this font (sans-serif)
