### ISSUE TITLE
TERRIBLE BOT!

### ISSUE THREAD

**Issue by ProHyphonzDaCoder** [roefinoavrililo/Discord.JS-Leveling-Bot#7]
This code is so garbage nothing ever works right and it has so many typos and errors a 0/5 DONT USE THIS CODE!!!

**Comment by ImSe4n** [comment]
b why :(

**Comment by ConnorAhern** [comment]
I'm probably going to make my own open source leveling bot once I get around to it.

**Comment by ConnorAhern** [comment]
Made it public again: https://github.com/hyphonz-bots/discord-leveling-bot

**Comment by ImSe4n** [comment]
not public again

**Comment by roefinoavrililo** [comment]
![output](https://user-images.githubusercontent.com/68174038/168426048-52ab65cc-2a2b-4a4f-8012-9195e62cbe37.gif)
